image: python:3.6

before_script:
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF- apt update
  - apt update
  - apt install -y apt-transport-https curl
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  - sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod artful main" > /etc/apt/sources.list.d/dotnetdev.list'
  - apt update
  - apt install -y mono-devel ca-certificates-mono dotnet-runtime-2.0.6 dotnet-sdk-2.1.104
  - pip install --upgrade setuptools pycparser
  - pip install --egg git+https://github.com/pythonnet/pythonnet -U --force
  - pip install -r requirements.txt

stages:
  - build
  - pages

build:
  stage: build
  script:
    - xbuild example/Example.sln /v minimal
    - python markdowndotnet.py -v "example/ExampleProject/bin/Debug/ApiExample.dll" "example/ExampleProject/bin/Debug/ApiExample.xml"
  artifacts:
    paths:
      - output/

pages:
  stage: pages
  before_script:
    - python install mkdocs mkdocs-material
  script:
    - python deploy.py
    - python -m mkdocs build
    - mv docs public
  artifacts:
    paths:
      - public

