image: pythonnet/pythonnet:python3.5-mono4.8.0-pythonnet2.3.0

stages:
  - build
  - deploy

before_script:
    - python -m pip install -r requirements.txt
    - python -m pip install mkdocs mkdocs-material

build:
  stage: build
  script:
    - xbuild example/Example.sln /v:minimal
    - python markdowndotnet.py -v "example/ExampleProject/bin/Debug/ApiExample.dll" "example/ExampleProject/bin/Debug/ApiExample.xml"
  artifacts:
    paths:
      - output

pages:
  stage: deploy
  script:
    - python deploy.py
    - python -m mkdocs build -d public
  artifacts:
    paths:
      - public
