dist: trusty
sudo: false
language: python

cache:
  apt: true

python:
  - "3.6"
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
      - dotnet-hostfxr-2.0.0
      - dotnet-runtime-2.0.0
      - dotnet-sdk-2.0.0

install:
  - pip install --upgrade setuptools
  - pip install pycparser
  - pip install --egg git+https://github.com/pythonnet/pythonnet -U --force
  - pip install -r requirements.txt
script:
  - xbuild example/ExampleSolution.sln /v:minimal
  - python markdowndotnet.py -v "example/ExampleProject/bin/Debug/ExampleProject.dll" "example/ExampleProject/bin/Debug/ExampleProject.xml"

after_success:
  - pip install mkdocs mkdocs-material
  - python deploy.py
  - python -m mkdocs build

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: site
  keep-history: true
  verbose: true
  on:
    branch: master