dist: trusty
sudo: false
language: python

python: 3.6
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    - sourceline: deb http://download.mono-project.com/repo/ubuntu trusty main
      key_url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA6A19B38D3D831EF
    packages:
      - mono-devel
      - ca-certificates-mono
      - dotnet-hostfxr-2.0.0
      - dotnet-runtime-2.0.0
      - dotnet-sdk-2.0.0

install:
  - pip install pycparser pythonnet

script:
  - mono ExampleSolution/ExampleSolution.sln
  - python markdowndotnet.py