site_name: 'markdowndotnet'
site_description: 'A Python markdown generator for C# libraries documentation'
site_author: 'Allan Galarza'
site_url: 'https://galarzaa90.github.io/markdowndotnet/'

repo_url: 'https://github.com/Galarzaa90/markdowndotnet'
edit_uri: ''

theme:
  name: material
  palette:
    primary: red
    accent: green
  feature:
    tabs: true
  logo:
    icon: assignment

markdown_extensions:
  - codehilite

extra:
  social:
    - type: 'github'
      link: 'https://github.com/galarzaa90'

pages:
  - Home: index.md